package com.example.idnp_sunshield.Activities;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import androidx.fragment.app.FragmentTransaction;
import android.os.Bundle;
import com.example.idnp_sunshield.Fragments.Alerts;
import com.example.idnp_sunshield.Fragments.Forecast;
import com.example.idnp_sunshield.Fragments.Health;
import com.example.idnp_sunshield.Fragments.Locations;
import com.example.idnp_sunshield.Fragments.UV_index;
import com.example.idnp_sunshield.R;
import com.example.idnp_sunshield.Services.BackgroundService;
import com.example.idnp_sunshield.Services.ForegroundService;
import com.example.idnp_sunshield.SharePreferences.LocationPreferences;
import com.example.idnp_sunshield.databinding.ActivityMainBinding;
import android.content.Intent;

public class MainActivity extends AppCompatActivity {
    // Declaration of the class generated by View Binding for the activity
    ActivityMainBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Inflate the activity layout using View Binding
        binding = ActivityMainBinding.inflate(getLayoutInflater());

        // Set the activity content to the root of the inflated layout
        setContentView(binding.getRoot());

        startBackgroundService();


        // Replace the content of the fragment container with the UV_index fragment when the activity starts

        //replaceFragment(new UV_index());
        //replaceFragment(new Locations());
        // Crear una instancia de LocationPreferences

        // Inicia el servicio en primer plano
        Intent serviceIntent = new Intent(this, ForegroundService.class);
        serviceIntent.putExtra("inputExtra", "Estoy ejecutando un servicio en primer plano");
        ContextCompat.startForegroundService(this, serviceIntent);

        LocationPreferences locationPreferences = new LocationPreferences(getApplicationContext());
        locationPreferences.clear();

        System.out.println("BOOLEAN MAIN "+locationPreferences.hasLocationData());
        // Verificar si hay datos en SharedPreferences
        if (locationPreferences.hasLocationData()) {
            // Si hay datos, iniciar el UV_index fragment
            replaceFragment(new UV_index());
        } else {
            // Si no hay datos, iniciar el Locations fragment
            replaceFragment(new Locations());
        }
        // Set up the listener for item selection in the bottom navigation bar
        binding.bottomNavigationView.setOnItemSelectedListener(item -> {
            // Determine which item in the navigation bar has been selected and replace the corresponding fragment
            if (item.getItemId() == R.id.uv_index) {
                replaceFragment(new UV_index());
            } else if (item.getItemId() == R.id.forecast) {
                replaceFragment(new Forecast());
            } else if (item.getItemId() == R.id.health) {
                replaceFragment(new Health());
            } else if (item.getItemId() == R.id.alerts) {
                replaceFragment(new Alerts());
                //replaceFragment(new Locations());
            }
            // Indicate that the item selection has been handled
            return true;
        });
    }

    // Método para iniciar el servicio en segundo plano
    private void startBackgroundService() {
        Intent serviceIntent = new Intent(this, BackgroundService.class);
        startService(serviceIntent);
    }

    // Method to replace the fragment in the container
    private void replaceFragment(Fragment fragment){
        // Get the fragment manager and start a fragment transaction
        FragmentManager fragmentManager = getSupportFragmentManager();
        FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();

        // Replace the content of the container with the new fragment
        fragmentTransaction.replace(R.id.frame_container, fragment);

        // Confirm the transaction
        fragmentTransaction.commit();
    }

    @Override
    protected void onStart() {
        super.onStart();

        // Detén el servicio en primer plano cuando la aplicación está en uso
        Intent serviceIntent = new Intent(this, ForegroundService.class);
        stopService(serviceIntent);
    }

    @Override
    protected void onStop() {
        super.onStop();

        if (!isChangingConfigurations()) {
            // Inicia el servicio en primer plano cuando la aplicación no está en uso
            Intent serviceIntent = new Intent(this, ForegroundService.class);
            serviceIntent.putExtra("inputExtra", "La aplicación no está en uso, iniciando el servicio en primer plano");
            ContextCompat.startForegroundService(this, serviceIntent);
        }
    }
}
